### ISSUE TITLE
plenty of /home/doug/-ness

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [DougBeney/Emacs-Config#1]
This is great! Thanks for sharing it.

However...  Do you see all the _/home/doug/_'s?

```lisp
;; Path
(setenv "PATH" (concat
                "/usr/bin:"
                "/usr/local/bin:"
                "/home/doug/.gem/bin:"
                "/home/doug/.local/bin:"
                "/home/doug/.npm/bin:"
                (getenv "PATH")))

(add-to-list 'exec-path "/home/doug/.npm/bin")
```

I am not a programmer, but isn't there a way to get environment variables, such as PATH, from another file (`~/.profile` or `~/.zshrc`, for example), or directly query the running environment, and then inject the bits you want into the config at runtime?

I know this is written primarily for yourself, but what happens when you pull your `~/.emac.d` onto a remote machine and discover it doesn't work because your USERDIR is, for example, `/users/dbeney/`?

`===EDIT===`
Is that what `(getenv "PATH")` does? If so, why all the things before it?

**Comment by DougBeney** [comment]
On remote machines I just use [Sanemacs](https://sanemacs.com/) with no further configuration as I don't normally need all the bells and whistles of this config.

I believe I needed these for certain modes that had different paths for whatever reason. Like how lsp-mode for ruby required solargraph which was in ~/.gem/bin

There's definitely a better way to do this though. You could use `(expand-file-name "~/.gem/bin")`and it will return the absolute path - `/home/doug/.gem/bin`. I believe it will even convert your "UNIX-style pathname" to a Windows one if that is the OS you're on.

`(getenv "PATH")` is for getting the current `PATH` variable. So, by default your `PATH` variable will contain locations like:

- /bin
- /usr/bin
- /usr/local/bin

If I didn't include that `getenv` part, I would no longer be able to run programs in the unmentioned directories.
